import type { InsertEmoji, InsertEmojiPage } from "@shared/schema";

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export const EMOJI_DATA: InsertEmoji[] = [
  // Smileys & Emotion
  { emoji: "😀", name: "Grinning Face", slug: "grinning-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["happy", "smile", "grin", "joy"], description: "A yellow face with a big grin showing upper teeth." },
  { emoji: "😃", name: "Grinning Face with Big Eyes", slug: "grinning-face-big-eyes", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["happy", "smile", "excited"], description: "A smiling face with open mouth and big eyes." },
  { emoji: "😄", name: "Grinning Face with Smiling Eyes", slug: "grinning-face-smiling-eyes", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["happy", "laugh", "joy"], description: "A grinning face with happy closed eyes." },
  { emoji: "😁", name: "Beaming Face with Smiling Eyes", slug: "beaming-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["grin", "happy", "beam"], description: "A face beaming with happiness." },
  { emoji: "😆", name: "Grinning Squinting Face", slug: "grinning-squinting-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["laugh", "satisfied", "happy"], description: "A face with a big grin and squinted eyes." },
  { emoji: "😅", name: "Grinning Face with Sweat", slug: "grinning-face-sweat", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["nervous", "relief", "phew"], description: "A smiling face with a drop of sweat." },
  { emoji: "🤣", name: "Rolling on the Floor Laughing", slug: "rofl", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["rofl", "lol", "hilarious", "laugh"], description: "Rolling on the floor laughing." },
  { emoji: "😂", name: "Face with Tears of Joy", slug: "tears-of-joy", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["laugh", "cry", "happy", "lol", "funny"], description: "A face laughing so hard it's crying." },
  { emoji: "🙂", name: "Slightly Smiling Face", slug: "slightly-smiling-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["smile", "okay", "fine"], description: "A face with a slight smile." },
  { emoji: "🙃", name: "Upside-Down Face", slug: "upside-down-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["sarcasm", "silly", "irony"], description: "A face turned upside down." },
  { emoji: "😉", name: "Winking Face", slug: "winking-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["wink", "flirt", "joke"], description: "A face winking with one eye closed." },
  { emoji: "😊", name: "Smiling Face with Smiling Eyes", slug: "smiling-face-smiling-eyes", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["happy", "blush", "warm", "smile"], description: "A warm smiling face." },
  { emoji: "😇", name: "Smiling Face with Halo", slug: "smiling-face-halo", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["angel", "innocent", "good"], description: "A smiling face with a halo above." },
  { emoji: "🥰", name: "Smiling Face with Hearts", slug: "smiling-face-hearts", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["love", "adore", "hearts", "crush"], description: "A face surrounded by hearts, feeling loved." },
  { emoji: "😍", name: "Smiling Face with Heart-Eyes", slug: "heart-eyes", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["love", "crush", "beautiful", "adore"], description: "A face with hearts for eyes." },
  { emoji: "🤩", name: "Star-Struck", slug: "star-struck", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["wow", "amazing", "star", "excited"], description: "A face with stars for eyes, amazed." },
  { emoji: "😘", name: "Face Blowing a Kiss", slug: "face-blowing-kiss", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["kiss", "love", "flirt"], description: "A face blowing a kiss." },
  { emoji: "😗", name: "Kissing Face", slug: "kissing-face", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["kiss", "lips"], description: "A face with puckered lips." },
  { emoji: "😚", name: "Kissing Face with Closed Eyes", slug: "kissing-face-closed-eyes", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["kiss", "love"], description: "A face kissing with eyes closed." },
  { emoji: "😋", name: "Face Savoring Food", slug: "face-savoring-food", category: "Smileys & Emotion", subcategory: "face-tongue", keywords: ["yummy", "delicious", "food", "tasty"], description: "A face licking its lips." },
  { emoji: "😛", name: "Face with Tongue", slug: "face-with-tongue", category: "Smileys & Emotion", subcategory: "face-tongue", keywords: ["tongue", "silly", "playful"], description: "A face sticking out its tongue." },
  { emoji: "😜", name: "Winking Face with Tongue", slug: "winking-face-tongue", category: "Smileys & Emotion", subcategory: "face-tongue", keywords: ["wink", "tongue", "joke", "playful"], description: "A winking face with tongue out." },
  { emoji: "🤪", name: "Zany Face", slug: "zany-face", category: "Smileys & Emotion", subcategory: "face-tongue", keywords: ["crazy", "wild", "silly", "goofy"], description: "A wild, zany face." },
  { emoji: "😝", name: "Squinting Face with Tongue", slug: "squinting-face-tongue", category: "Smileys & Emotion", subcategory: "face-tongue", keywords: ["tongue", "disgusted", "silly"], description: "A face squinting with tongue out." },
  { emoji: "🤑", name: "Money-Mouth Face", slug: "money-mouth-face", category: "Smileys & Emotion", subcategory: "face-tongue", keywords: ["money", "rich", "dollar", "cash"], description: "A face with dollar sign eyes and tongue." },
  { emoji: "🤗", name: "Hugging Face", slug: "hugging-face", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["hug", "love", "embrace", "warm"], description: "A face offering a hug." },
  { emoji: "🤭", name: "Face with Hand Over Mouth", slug: "face-hand-over-mouth", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["oops", "giggle", "shy"], description: "A face covering its mouth." },
  { emoji: "🤫", name: "Shushing Face", slug: "shushing-face", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["quiet", "shh", "secret", "silence"], description: "A face with finger to lips." },
  { emoji: "🤔", name: "Thinking Face", slug: "thinking-face", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["think", "hmm", "ponder", "consider"], description: "A face deep in thought." },
  { emoji: "🤐", name: "Zipper-Mouth Face", slug: "zipper-mouth-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["quiet", "mute", "secret", "zip"], description: "A face with a zipper for a mouth." },
  { emoji: "🤨", name: "Face with Raised Eyebrow", slug: "raised-eyebrow", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["skeptical", "suspicious", "doubt"], description: "A face with one raised eyebrow." },
  { emoji: "😐", name: "Neutral Face", slug: "neutral-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["meh", "blank", "indifferent"], description: "A face with a straight mouth." },
  { emoji: "😑", name: "Expressionless Face", slug: "expressionless-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["blank", "bored", "unamused"], description: "A face with flat closed eyes." },
  { emoji: "😶", name: "Face Without Mouth", slug: "face-without-mouth", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["speechless", "mute", "silent"], description: "A face without a mouth." },
  { emoji: "😏", name: "Smirking Face", slug: "smirking-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["smirk", "flirt", "suggestive", "sly"], description: "A face with a sly smirk." },
  { emoji: "😒", name: "Unamused Face", slug: "unamused-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["unamused", "bored", "side-eye"], description: "An unamused, side-glancing face." },
  { emoji: "🙄", name: "Face with Rolling Eyes", slug: "rolling-eyes", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["eyeroll", "annoyed", "whatever"], description: "A face rolling its eyes." },
  { emoji: "😬", name: "Grimacing Face", slug: "grimacing-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["awkward", "nervous", "cringe"], description: "A face grimacing with bared teeth." },
  { emoji: "🤥", name: "Lying Face", slug: "lying-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["lie", "pinocchio", "dishonest"], description: "A face with a growing nose." },
  { emoji: "😌", name: "Relieved Face", slug: "relieved-face", category: "Smileys & Emotion", subcategory: "face-sleepy", keywords: ["relieved", "relaxed", "peaceful"], description: "A peaceful, relieved face." },
  { emoji: "😔", name: "Pensive Face", slug: "pensive-face", category: "Smileys & Emotion", subcategory: "face-sleepy", keywords: ["sad", "pensive", "thoughtful"], description: "A face looking down, pensive." },
  { emoji: "😪", name: "Sleepy Face", slug: "sleepy-face", category: "Smileys & Emotion", subcategory: "face-sleepy", keywords: ["sleepy", "tired", "snot"], description: "A sleepy face with a snot bubble." },
  { emoji: "🤤", name: "Drooling Face", slug: "drooling-face", category: "Smileys & Emotion", subcategory: "face-sleepy", keywords: ["drool", "hungry", "desire"], description: "A face drooling." },
  { emoji: "😴", name: "Sleeping Face", slug: "sleeping-face", category: "Smileys & Emotion", subcategory: "face-sleepy", keywords: ["sleep", "zzz", "rest", "tired"], description: "A sleeping face with ZZZ." },
  { emoji: "😷", name: "Face with Medical Mask", slug: "face-medical-mask", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["sick", "mask", "covid", "ill"], description: "A face wearing a medical mask." },
  { emoji: "🤒", name: "Face with Thermometer", slug: "face-thermometer", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["sick", "fever", "ill"], description: "A sick face with a thermometer." },
  { emoji: "🤕", name: "Face with Head-Bandage", slug: "face-head-bandage", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["hurt", "injured", "bandage"], description: "A face with a bandaged head." },
  { emoji: "🤢", name: "Nauseated Face", slug: "nauseated-face", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["sick", "nausea", "gross", "disgusted"], description: "A green, nauseated face." },
  { emoji: "🤮", name: "Face Vomiting", slug: "face-vomiting", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["vomit", "sick", "gross"], description: "A face throwing up." },
  { emoji: "🥵", name: "Hot Face", slug: "hot-face", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["hot", "heat", "sweating", "overheated"], description: "A red face overheating." },
  { emoji: "🥶", name: "Cold Face", slug: "cold-face", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["cold", "freezing", "frozen"], description: "A blue face frozen from cold." },
  { emoji: "😵", name: "Face with Crossed-Out Eyes", slug: "face-crossed-out-eyes", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["dizzy", "dead", "knocked out"], description: "A face with X eyes, dizzy." },
  { emoji: "🥴", name: "Woozy Face", slug: "woozy-face", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["drunk", "tipsy", "woozy", "disoriented"], description: "A woozy, disoriented face." },
  { emoji: "😱", name: "Face Screaming in Fear", slug: "face-screaming-fear", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["scream", "scared", "horror", "shocked"], description: "A face screaming in fear." },
  { emoji: "😨", name: "Fearful Face", slug: "fearful-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["fear", "scared", "worried"], description: "A face showing fear." },
  { emoji: "😰", name: "Anxious Face with Sweat", slug: "anxious-face-sweat", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["anxious", "nervous", "worried"], description: "An anxious face with sweat." },
  { emoji: "😢", name: "Crying Face", slug: "crying-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["cry", "sad", "tear", "upset"], description: "A face with a single tear." },
  { emoji: "😭", name: "Loudly Crying Face", slug: "loudly-crying-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["cry", "sob", "sad", "bawl"], description: "A face crying loudly with streams of tears." },
  { emoji: "😤", name: "Face with Steam From Nose", slug: "face-steam-nose", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["angry", "frustrated", "triumph"], description: "A face with steam from its nose." },
  { emoji: "😡", name: "Pouting Face", slug: "pouting-face", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["angry", "mad", "rage", "furious"], description: "A red, angry pouting face." },
  { emoji: "😠", name: "Angry Face", slug: "angry-face", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["angry", "mad", "grumpy"], description: "An angry, frowning face." },
  { emoji: "🤬", name: "Face with Symbols on Mouth", slug: "face-symbols-mouth", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["swear", "curse", "angry", "censored"], description: "A face swearing with symbols." },
  { emoji: "😈", name: "Smiling Face with Horns", slug: "smiling-face-horns", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["devil", "evil", "naughty", "mischief"], description: "A purple smiling devil face." },
  { emoji: "👿", name: "Angry Face with Horns", slug: "angry-face-horns", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["devil", "angry", "evil"], description: "An angry purple devil face." },
  { emoji: "💀", name: "Skull", slug: "skull", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["dead", "death", "skeleton", "danger"], description: "A human skull." },
  { emoji: "☠️", name: "Skull and Crossbones", slug: "skull-crossbones", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["death", "danger", "poison", "pirate"], description: "Skull with crossbones." },
  { emoji: "💩", name: "Pile of Poo", slug: "pile-of-poo", category: "Smileys & Emotion", subcategory: "face-costume", keywords: ["poop", "crap", "funny", "poo"], description: "A smiling pile of poo." },
  { emoji: "🤡", name: "Clown Face", slug: "clown-face", category: "Smileys & Emotion", subcategory: "face-costume", keywords: ["clown", "funny", "circus"], description: "A colorful clown face." },
  { emoji: "👻", name: "Ghost", slug: "ghost", category: "Smileys & Emotion", subcategory: "face-costume", keywords: ["ghost", "halloween", "spooky", "boo"], description: "A cute ghost." },
  { emoji: "👽", name: "Alien", slug: "alien", category: "Smileys & Emotion", subcategory: "face-costume", keywords: ["alien", "ufo", "space", "extraterrestrial"], description: "An alien face." },
  { emoji: "🤖", name: "Robot", slug: "robot", category: "Smileys & Emotion", subcategory: "face-costume", keywords: ["robot", "machine", "ai", "tech"], description: "A robot face." },
  { emoji: "😺", name: "Grinning Cat", slug: "grinning-cat", category: "Smileys & Emotion", subcategory: "cat-face", keywords: ["cat", "happy", "grin"], description: "A happy grinning cat." },
  { emoji: "😻", name: "Smiling Cat with Heart-Eyes", slug: "smiling-cat-heart-eyes", category: "Smileys & Emotion", subcategory: "cat-face", keywords: ["cat", "love", "heart"], description: "A cat with heart-shaped eyes." },
  { emoji: "🙈", name: "See-No-Evil Monkey", slug: "see-no-evil-monkey", category: "Smileys & Emotion", subcategory: "monkey-face", keywords: ["monkey", "shy", "hide", "embarrassed"], description: "A monkey covering its eyes." },
  { emoji: "🙉", name: "Hear-No-Evil Monkey", slug: "hear-no-evil-monkey", category: "Smileys & Emotion", subcategory: "monkey-face", keywords: ["monkey", "hear", "ignore"], description: "A monkey covering its ears." },
  { emoji: "🙊", name: "Speak-No-Evil Monkey", slug: "speak-no-evil-monkey", category: "Smileys & Emotion", subcategory: "monkey-face", keywords: ["monkey", "quiet", "oops"], description: "A monkey covering its mouth." },

  // Hearts & Love
  { emoji: "❤️", name: "Red Heart", slug: "red-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "heart", "red", "valentine", "romance"], description: "A classic red heart." },
  { emoji: "🧡", name: "Orange Heart", slug: "orange-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "orange", "heart"], description: "An orange heart." },
  { emoji: "💛", name: "Yellow Heart", slug: "yellow-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "yellow", "heart", "friendship"], description: "A yellow heart." },
  { emoji: "💚", name: "Green Heart", slug: "green-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "green", "heart", "nature"], description: "A green heart." },
  { emoji: "💙", name: "Blue Heart", slug: "blue-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "blue", "heart", "trust"], description: "A blue heart." },
  { emoji: "💜", name: "Purple Heart", slug: "purple-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "purple", "heart"], description: "A purple heart." },
  { emoji: "🖤", name: "Black Heart", slug: "black-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "black", "heart", "dark"], description: "A black heart." },
  { emoji: "🤍", name: "White Heart", slug: "white-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "white", "heart", "pure"], description: "A white heart." },
  { emoji: "🤎", name: "Brown Heart", slug: "brown-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "brown", "heart"], description: "A brown heart." },
  { emoji: "💕", name: "Two Hearts", slug: "two-hearts", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "hearts", "couple", "romance"], description: "Two revolving hearts." },
  { emoji: "💞", name: "Revolving Hearts", slug: "revolving-hearts", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "hearts", "spinning"], description: "Hearts revolving around each other." },
  { emoji: "💓", name: "Beating Heart", slug: "beating-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "heartbeat", "alive"], description: "A beating, pulsing heart." },
  { emoji: "💗", name: "Growing Heart", slug: "growing-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "growing", "bigger"], description: "A heart growing bigger." },
  { emoji: "💖", name: "Sparkling Heart", slug: "sparkling-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "sparkle", "shine"], description: "A sparkling heart." },
  { emoji: "💘", name: "Heart with Arrow", slug: "heart-with-arrow", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "cupid", "valentine", "arrow"], description: "A heart struck by an arrow." },
  { emoji: "💝", name: "Heart with Ribbon", slug: "heart-with-ribbon", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "gift", "valentine", "ribbon"], description: "A heart wrapped with ribbon." },
  { emoji: "💟", name: "Heart Decoration", slug: "heart-decoration", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "decoration", "heart"], description: "A decorative heart." },
  { emoji: "❣️", name: "Heart Exclamation", slug: "heart-exclamation", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "exclamation", "emphasis"], description: "A heart used as an exclamation mark." },
  { emoji: "💔", name: "Broken Heart", slug: "broken-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["heartbreak", "sad", "breakup", "love"], description: "A heart broken in two." },
  { emoji: "💋", name: "Kiss Mark", slug: "kiss-mark", category: "Hearts & Love", subcategory: "heart", keywords: ["kiss", "lips", "love", "lipstick"], description: "A red kiss mark." },
  { emoji: "💑", name: "Couple with Heart", slug: "couple-with-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "couple", "romance", "relationship"], description: "A couple in love." },
  { emoji: "💏", name: "Kiss", slug: "kiss-emoji", category: "Hearts & Love", subcategory: "heart", keywords: ["kiss", "couple", "love", "romance"], description: "Two people kissing." },

  // Hand Gestures
  { emoji: "👋", name: "Waving Hand", slug: "waving-hand", category: "Hand Gestures", subcategory: "hand-fingers-open", keywords: ["wave", "hello", "goodbye", "hi"], description: "A hand waving hello or goodbye." },
  { emoji: "🤚", name: "Raised Back of Hand", slug: "raised-back-hand", category: "Hand Gestures", subcategory: "hand-fingers-open", keywords: ["hand", "stop", "raised"], description: "The back of a raised hand." },
  { emoji: "🖐️", name: "Hand with Fingers Splayed", slug: "hand-fingers-splayed", category: "Hand Gestures", subcategory: "hand-fingers-open", keywords: ["hand", "five", "high five"], description: "An open hand with fingers spread." },
  { emoji: "✋", name: "Raised Hand", slug: "raised-hand", category: "Hand Gestures", subcategory: "hand-fingers-open", keywords: ["stop", "high five", "hand", "raised"], description: "A raised hand." },
  { emoji: "👌", name: "OK Hand", slug: "ok-hand", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["ok", "perfect", "agree", "good"], description: "A hand making the OK sign." },
  { emoji: "🤌", name: "Pinched Fingers", slug: "pinched-fingers", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["italian", "what", "chef", "gesture"], description: "Fingers pressed together pointing up." },
  { emoji: "✌️", name: "Victory Hand", slug: "victory-hand", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["peace", "victory", "two", "v"], description: "A hand showing the peace sign." },
  { emoji: "🤞", name: "Crossed Fingers", slug: "crossed-fingers", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["luck", "hope", "fingers crossed"], description: "Fingers crossed for good luck." },
  { emoji: "🤟", name: "Love-You Gesture", slug: "love-you-gesture", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["love", "ily", "sign language", "rock"], description: "I love you in sign language." },
  { emoji: "🤘", name: "Sign of the Horns", slug: "sign-of-horns", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["rock", "metal", "horns", "cool"], description: "Rock on hand sign." },
  { emoji: "🤙", name: "Call Me Hand", slug: "call-me-hand", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["call", "shaka", "hang loose", "phone"], description: "A call me hand gesture." },
  { emoji: "👈", name: "Backhand Index Pointing Left", slug: "pointing-left", category: "Hand Gestures", subcategory: "hand-single-finger", keywords: ["left", "point", "direction"], description: "A hand pointing left." },
  { emoji: "👉", name: "Backhand Index Pointing Right", slug: "pointing-right", category: "Hand Gestures", subcategory: "hand-single-finger", keywords: ["right", "point", "direction"], description: "A hand pointing right." },
  { emoji: "👆", name: "Backhand Index Pointing Up", slug: "pointing-up", category: "Hand Gestures", subcategory: "hand-single-finger", keywords: ["up", "point", "above"], description: "A hand pointing up." },
  { emoji: "👇", name: "Backhand Index Pointing Down", slug: "pointing-down", category: "Hand Gestures", subcategory: "hand-single-finger", keywords: ["down", "point", "below"], description: "A hand pointing down." },
  { emoji: "☝️", name: "Index Pointing Up", slug: "index-pointing-up", category: "Hand Gestures", subcategory: "hand-single-finger", keywords: ["up", "one", "point", "attention"], description: "An index finger pointing up." },
  { emoji: "👍", name: "Thumbs Up", slug: "thumbs-up", category: "Hand Gestures", subcategory: "hand-fingers-closed", keywords: ["like", "approve", "good", "yes", "thumbsup"], description: "A thumbs up hand gesture." },
  { emoji: "👎", name: "Thumbs Down", slug: "thumbs-down", category: "Hand Gestures", subcategory: "hand-fingers-closed", keywords: ["dislike", "bad", "no", "thumbsdown"], description: "A thumbs down hand gesture." },
  { emoji: "✊", name: "Raised Fist", slug: "raised-fist", category: "Hand Gestures", subcategory: "hand-fingers-closed", keywords: ["fist", "power", "solidarity", "strong"], description: "A raised fist." },
  { emoji: "👊", name: "Oncoming Fist", slug: "oncoming-fist", category: "Hand Gestures", subcategory: "hand-fingers-closed", keywords: ["punch", "fist bump", "bro"], description: "A fist coming toward you." },
  { emoji: "🤛", name: "Left-Facing Fist", slug: "left-facing-fist", category: "Hand Gestures", subcategory: "hand-fingers-closed", keywords: ["fist bump", "left"], description: "A left-facing fist." },
  { emoji: "🤜", name: "Right-Facing Fist", slug: "right-facing-fist", category: "Hand Gestures", subcategory: "hand-fingers-closed", keywords: ["fist bump", "right"], description: "A right-facing fist." },
  { emoji: "👏", name: "Clapping Hands", slug: "clapping-hands", category: "Hand Gestures", subcategory: "hands", keywords: ["clap", "applause", "bravo", "congratulations"], description: "Two hands clapping." },
  { emoji: "🙌", name: "Raising Hands", slug: "raising-hands", category: "Hand Gestures", subcategory: "hands", keywords: ["celebrate", "hooray", "hands up", "praise"], description: "Two raised hands celebrating." },
  { emoji: "👐", name: "Open Hands", slug: "open-hands", category: "Hand Gestures", subcategory: "hands", keywords: ["open", "hands", "jazz hands"], description: "Two open hands." },
  { emoji: "🤝", name: "Handshake", slug: "handshake", category: "Hand Gestures", subcategory: "hands", keywords: ["handshake", "deal", "agreement", "hello"], description: "Two hands shaking." },
  { emoji: "🙏", name: "Folded Hands", slug: "folded-hands", category: "Hand Gestures", subcategory: "hands", keywords: ["pray", "please", "thank you", "hope", "namaste"], description: "Two hands pressed together." },
  { emoji: "💪", name: "Flexed Biceps", slug: "flexed-biceps", category: "Hand Gestures", subcategory: "body-parts", keywords: ["strong", "muscle", "flex", "power", "gym"], description: "A flexed bicep muscle." },

  // People & Body
  { emoji: "👶", name: "Baby", slug: "baby", category: "People & Body", subcategory: "person", keywords: ["baby", "infant", "child", "newborn"], description: "A baby face." },
  { emoji: "👦", name: "Boy", slug: "boy", category: "People & Body", subcategory: "person", keywords: ["boy", "kid", "child", "young"], description: "A young boy." },
  { emoji: "👧", name: "Girl", slug: "girl", category: "People & Body", subcategory: "person", keywords: ["girl", "kid", "child", "young"], description: "A young girl." },
  { emoji: "👨", name: "Man", slug: "man", category: "People & Body", subcategory: "person", keywords: ["man", "male", "adult", "guy"], description: "An adult man." },
  { emoji: "👩", name: "Woman", slug: "woman", category: "People & Body", subcategory: "person", keywords: ["woman", "female", "adult", "lady"], description: "An adult woman." },
  { emoji: "🧑", name: "Person", slug: "person", category: "People & Body", subcategory: "person", keywords: ["person", "adult", "gender-neutral"], description: "A gender-neutral person." },
  { emoji: "👴", name: "Old Man", slug: "old-man", category: "People & Body", subcategory: "person", keywords: ["old", "grandpa", "elderly", "grandfather"], description: "An elderly man." },
  { emoji: "👵", name: "Old Woman", slug: "old-woman", category: "People & Body", subcategory: "person", keywords: ["old", "grandma", "elderly", "grandmother"], description: "An elderly woman." },

  // Animals & Nature
  { emoji: "🐶", name: "Dog Face", slug: "dog-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["dog", "puppy", "pet", "cute", "woof"], description: "A cute dog face." },
  { emoji: "🐱", name: "Cat Face", slug: "cat-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["cat", "kitten", "pet", "cute", "meow"], description: "A cute cat face." },
  { emoji: "🐭", name: "Mouse Face", slug: "mouse-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["mouse", "rodent", "cute"], description: "A cute mouse face." },
  { emoji: "🐹", name: "Hamster", slug: "hamster", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["hamster", "pet", "cute", "rodent"], description: "A cute hamster face." },
  { emoji: "🐰", name: "Rabbit Face", slug: "rabbit-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["rabbit", "bunny", "cute", "easter"], description: "A cute rabbit face." },
  { emoji: "🦊", name: "Fox", slug: "fox", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["fox", "animal", "cute", "clever"], description: "A fox face." },
  { emoji: "🐻", name: "Bear", slug: "bear", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["bear", "animal", "cute", "teddy"], description: "A bear face." },
  { emoji: "🐼", name: "Panda", slug: "panda", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["panda", "bear", "cute", "china"], description: "A panda face." },
  { emoji: "🐨", name: "Koala", slug: "koala", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["koala", "animal", "cute", "australia"], description: "A koala face." },
  { emoji: "🐯", name: "Tiger Face", slug: "tiger-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["tiger", "animal", "fierce", "striped"], description: "A tiger face." },
  { emoji: "🦁", name: "Lion", slug: "lion", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["lion", "king", "animal", "fierce"], description: "A lion face." },
  { emoji: "🐮", name: "Cow Face", slug: "cow-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["cow", "moo", "animal", "farm"], description: "A cow face." },
  { emoji: "🐷", name: "Pig Face", slug: "pig-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["pig", "oink", "animal", "farm"], description: "A pig face." },
  { emoji: "🐸", name: "Frog", slug: "frog", category: "Animals & Nature", subcategory: "animal-amphibian", keywords: ["frog", "toad", "ribbit", "amphibian"], description: "A frog face." },
  { emoji: "🐵", name: "Monkey Face", slug: "monkey-face", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["monkey", "animal", "primate", "cute"], description: "A monkey face." },
  { emoji: "🐔", name: "Chicken", slug: "chicken", category: "Animals & Nature", subcategory: "animal-bird", keywords: ["chicken", "bird", "farm", "cluck"], description: "A chicken." },
  { emoji: "🐧", name: "Penguin", slug: "penguin", category: "Animals & Nature", subcategory: "animal-bird", keywords: ["penguin", "bird", "cold", "cute"], description: "A penguin." },
  { emoji: "🐦", name: "Bird", slug: "bird", category: "Animals & Nature", subcategory: "animal-bird", keywords: ["bird", "tweet", "fly", "chirp"], description: "A bird." },
  { emoji: "🦅", name: "Eagle", slug: "eagle", category: "Animals & Nature", subcategory: "animal-bird", keywords: ["eagle", "bird", "america", "freedom"], description: "An eagle." },
  { emoji: "🦋", name: "Butterfly", slug: "butterfly", category: "Animals & Nature", subcategory: "animal-bug", keywords: ["butterfly", "insect", "beautiful", "nature"], description: "A butterfly." },
  { emoji: "🐛", name: "Bug", slug: "bug", category: "Animals & Nature", subcategory: "animal-bug", keywords: ["bug", "insect", "caterpillar"], description: "A green bug." },
  { emoji: "🐝", name: "Honeybee", slug: "honeybee", category: "Animals & Nature", subcategory: "animal-bug", keywords: ["bee", "honey", "buzz", "insect"], description: "A honeybee." },
  { emoji: "🐍", name: "Snake", slug: "snake", category: "Animals & Nature", subcategory: "animal-reptile", keywords: ["snake", "reptile", "hiss"], description: "A snake." },
  { emoji: "🐢", name: "Turtle", slug: "turtle", category: "Animals & Nature", subcategory: "animal-reptile", keywords: ["turtle", "slow", "shell", "reptile"], description: "A turtle." },
  { emoji: "🐠", name: "Tropical Fish", slug: "tropical-fish", category: "Animals & Nature", subcategory: "animal-marine", keywords: ["fish", "tropical", "ocean", "aquarium"], description: "A tropical fish." },
  { emoji: "🐬", name: "Dolphin", slug: "dolphin", category: "Animals & Nature", subcategory: "animal-marine", keywords: ["dolphin", "ocean", "smart", "flipper"], description: "A dolphin." },
  { emoji: "🐳", name: "Spouting Whale", slug: "spouting-whale", category: "Animals & Nature", subcategory: "animal-marine", keywords: ["whale", "ocean", "spout", "big"], description: "A whale spouting water." },
  { emoji: "🦈", name: "Shark", slug: "shark", category: "Animals & Nature", subcategory: "animal-marine", keywords: ["shark", "ocean", "danger", "jaws"], description: "A shark." },
  { emoji: "🐙", name: "Octopus", slug: "octopus", category: "Animals & Nature", subcategory: "animal-marine", keywords: ["octopus", "tentacles", "ocean"], description: "An octopus." },
  { emoji: "🦄", name: "Unicorn", slug: "unicorn", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["unicorn", "magical", "fantasy", "rainbow", "horse"], description: "A unicorn." },

  // Plants & Flowers
  { emoji: "🌸", name: "Cherry Blossom", slug: "cherry-blossom", category: "Plants & Flowers", subcategory: "plant-flower", keywords: ["flower", "spring", "cherry", "blossom", "japan"], description: "A pink cherry blossom." },
  { emoji: "🌹", name: "Rose", slug: "rose", category: "Plants & Flowers", subcategory: "plant-flower", keywords: ["rose", "flower", "love", "romance", "red"], description: "A red rose." },
  { emoji: "🌺", name: "Hibiscus", slug: "hibiscus", category: "Plants & Flowers", subcategory: "plant-flower", keywords: ["flower", "hibiscus", "tropical"], description: "A hibiscus flower." },
  { emoji: "🌻", name: "Sunflower", slug: "sunflower", category: "Plants & Flowers", subcategory: "plant-flower", keywords: ["sunflower", "flower", "sun", "yellow"], description: "A sunflower." },
  { emoji: "🌼", name: "Blossom", slug: "blossom", category: "Plants & Flowers", subcategory: "plant-flower", keywords: ["flower", "blossom", "spring", "nature"], description: "A flower in bloom." },
  { emoji: "🌷", name: "Tulip", slug: "tulip", category: "Plants & Flowers", subcategory: "plant-flower", keywords: ["tulip", "flower", "spring", "pink"], description: "A pink tulip." },
  { emoji: "🌱", name: "Seedling", slug: "seedling", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["plant", "seedling", "grow", "sprout", "nature"], description: "A small green seedling." },
  { emoji: "🌲", name: "Evergreen Tree", slug: "evergreen-tree", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["tree", "pine", "evergreen", "forest"], description: "An evergreen tree." },
  { emoji: "🌳", name: "Deciduous Tree", slug: "deciduous-tree", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["tree", "nature", "forest"], description: "A leafy tree." },
  { emoji: "🌴", name: "Palm Tree", slug: "palm-tree", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["palm", "tree", "tropical", "beach", "vacation"], description: "A palm tree." },
  { emoji: "🌵", name: "Cactus", slug: "cactus", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["cactus", "desert", "plant", "prickly"], description: "A cactus." },
  { emoji: "🍀", name: "Four Leaf Clover", slug: "four-leaf-clover", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["luck", "clover", "irish", "lucky", "shamrock"], description: "A four-leaf clover for luck." },
  { emoji: "🍁", name: "Maple Leaf", slug: "maple-leaf", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["maple", "leaf", "fall", "autumn", "canada"], description: "A maple leaf." },

  // Food & Drink
  { emoji: "🍎", name: "Red Apple", slug: "red-apple", category: "Food & Drink", subcategory: "food-fruit", keywords: ["apple", "fruit", "red", "healthy"], description: "A red apple." },
  { emoji: "🍊", name: "Tangerine", slug: "tangerine", category: "Food & Drink", subcategory: "food-fruit", keywords: ["orange", "tangerine", "fruit", "citrus"], description: "A tangerine." },
  { emoji: "🍋", name: "Lemon", slug: "lemon", category: "Food & Drink", subcategory: "food-fruit", keywords: ["lemon", "fruit", "sour", "citrus"], description: "A lemon." },
  { emoji: "🍌", name: "Banana", slug: "banana", category: "Food & Drink", subcategory: "food-fruit", keywords: ["banana", "fruit", "yellow"], description: "A banana." },
  { emoji: "🍉", name: "Watermelon", slug: "watermelon", category: "Food & Drink", subcategory: "food-fruit", keywords: ["watermelon", "fruit", "summer", "juicy"], description: "A watermelon slice." },
  { emoji: "🍇", name: "Grapes", slug: "grapes", category: "Food & Drink", subcategory: "food-fruit", keywords: ["grapes", "fruit", "wine", "purple"], description: "A bunch of grapes." },
  { emoji: "🍓", name: "Strawberry", slug: "strawberry", category: "Food & Drink", subcategory: "food-fruit", keywords: ["strawberry", "fruit", "red", "sweet"], description: "A strawberry." },
  { emoji: "🍑", name: "Peach", slug: "peach", category: "Food & Drink", subcategory: "food-fruit", keywords: ["peach", "fruit", "butt"], description: "A peach." },
  { emoji: "🍒", name: "Cherries", slug: "cherries", category: "Food & Drink", subcategory: "food-fruit", keywords: ["cherry", "fruit", "red"], description: "A pair of cherries." },
  { emoji: "🥑", name: "Avocado", slug: "avocado", category: "Food & Drink", subcategory: "food-vegetable", keywords: ["avocado", "food", "green", "healthy"], description: "An avocado half." },
  { emoji: "🍔", name: "Hamburger", slug: "hamburger", category: "Food & Drink", subcategory: "food-prepared", keywords: ["burger", "food", "fast food", "meal"], description: "A hamburger." },
  { emoji: "🍕", name: "Pizza", slug: "pizza", category: "Food & Drink", subcategory: "food-prepared", keywords: ["pizza", "food", "italian", "slice"], description: "A slice of pizza." },
  { emoji: "🌮", name: "Taco", slug: "taco", category: "Food & Drink", subcategory: "food-prepared", keywords: ["taco", "food", "mexican"], description: "A taco." },
  { emoji: "🌯", name: "Burrito", slug: "burrito", category: "Food & Drink", subcategory: "food-prepared", keywords: ["burrito", "food", "mexican", "wrap"], description: "A burrito." },
  { emoji: "🍜", name: "Steaming Bowl", slug: "steaming-bowl", category: "Food & Drink", subcategory: "food-asian", keywords: ["ramen", "noodles", "soup", "food", "hot"], description: "A steaming bowl of noodles." },
  { emoji: "🍣", name: "Sushi", slug: "sushi", category: "Food & Drink", subcategory: "food-asian", keywords: ["sushi", "food", "japanese", "fish"], description: "A piece of sushi." },
  { emoji: "🍦", name: "Soft Ice Cream", slug: "soft-ice-cream", category: "Food & Drink", subcategory: "food-sweet", keywords: ["ice cream", "dessert", "sweet", "cone"], description: "A soft-serve ice cream cone." },
  { emoji: "🍩", name: "Doughnut", slug: "doughnut", category: "Food & Drink", subcategory: "food-sweet", keywords: ["donut", "doughnut", "sweet", "breakfast"], description: "A doughnut with frosting." },
  { emoji: "🍪", name: "Cookie", slug: "cookie", category: "Food & Drink", subcategory: "food-sweet", keywords: ["cookie", "sweet", "chocolate chip", "snack"], description: "A chocolate chip cookie." },
  { emoji: "🎂", name: "Birthday Cake", slug: "birthday-cake", category: "Food & Drink", subcategory: "food-sweet", keywords: ["cake", "birthday", "celebration", "party"], description: "A birthday cake with candle." },
  { emoji: "🍰", name: "Shortcake", slug: "shortcake", category: "Food & Drink", subcategory: "food-sweet", keywords: ["cake", "dessert", "sweet", "slice"], description: "A slice of cake." },
  { emoji: "☕", name: "Hot Beverage", slug: "hot-beverage", category: "Food & Drink", subcategory: "drink", keywords: ["coffee", "tea", "hot", "drink", "cafe"], description: "A hot cup of coffee or tea." },
  { emoji: "🍺", name: "Beer Mug", slug: "beer-mug", category: "Food & Drink", subcategory: "drink", keywords: ["beer", "drink", "alcohol", "cheers"], description: "A mug of beer." },
  { emoji: "🍷", name: "Wine Glass", slug: "wine-glass", category: "Food & Drink", subcategory: "drink", keywords: ["wine", "drink", "alcohol", "red wine"], description: "A glass of red wine." },
  { emoji: "🍸", name: "Cocktail Glass", slug: "cocktail-glass", category: "Food & Drink", subcategory: "drink", keywords: ["cocktail", "drink", "martini", "alcohol"], description: "A cocktail glass." },

  // Activities & Sports
  { emoji: "⚽", name: "Soccer Ball", slug: "soccer-ball", category: "Activities & Sports", subcategory: "sport", keywords: ["soccer", "football", "ball", "sport"], description: "A soccer ball." },
  { emoji: "🏀", name: "Basketball", slug: "basketball", category: "Activities & Sports", subcategory: "sport", keywords: ["basketball", "ball", "sport", "nba"], description: "A basketball." },
  { emoji: "🏈", name: "American Football", slug: "american-football", category: "Activities & Sports", subcategory: "sport", keywords: ["football", "american", "sport", "nfl"], description: "An American football." },
  { emoji: "⚾", name: "Baseball", slug: "baseball", category: "Activities & Sports", subcategory: "sport", keywords: ["baseball", "ball", "sport"], description: "A baseball." },
  { emoji: "🎾", name: "Tennis", slug: "tennis", category: "Activities & Sports", subcategory: "sport", keywords: ["tennis", "ball", "sport", "racket"], description: "A tennis ball." },
  { emoji: "🏐", name: "Volleyball", slug: "volleyball", category: "Activities & Sports", subcategory: "sport", keywords: ["volleyball", "ball", "sport"], description: "A volleyball." },
  { emoji: "🏆", name: "Trophy", slug: "trophy", category: "Activities & Sports", subcategory: "award", keywords: ["trophy", "winner", "champion", "award", "gold"], description: "A gold trophy." },
  { emoji: "🥇", name: "1st Place Medal", slug: "first-place-medal", category: "Activities & Sports", subcategory: "award", keywords: ["gold", "medal", "first", "winner"], description: "A gold medal." },
  { emoji: "🥈", name: "2nd Place Medal", slug: "second-place-medal", category: "Activities & Sports", subcategory: "award", keywords: ["silver", "medal", "second"], description: "A silver medal." },
  { emoji: "🥉", name: "3rd Place Medal", slug: "third-place-medal", category: "Activities & Sports", subcategory: "award", keywords: ["bronze", "medal", "third"], description: "A bronze medal." },
  { emoji: "🎮", name: "Video Game", slug: "video-game", category: "Activities & Sports", subcategory: "game", keywords: ["game", "gaming", "controller", "play", "console"], description: "A video game controller." },
  { emoji: "🎯", name: "Bullseye", slug: "bullseye", category: "Activities & Sports", subcategory: "game", keywords: ["target", "bullseye", "direct hit", "goal"], description: "A target with bullseye." },
  { emoji: "🎲", name: "Game Die", slug: "game-die", category: "Activities & Sports", subcategory: "game", keywords: ["dice", "game", "random", "luck"], description: "A six-sided die." },

  // Travel & Places
  { emoji: "🚗", name: "Automobile", slug: "automobile", category: "Travel & Places", subcategory: "transport-ground", keywords: ["car", "automobile", "drive", "vehicle"], description: "A red automobile." },
  { emoji: "🚕", name: "Taxi", slug: "taxi", category: "Travel & Places", subcategory: "transport-ground", keywords: ["taxi", "cab", "ride", "yellow"], description: "A taxi cab." },
  { emoji: "🚀", name: "Rocket", slug: "rocket", category: "Travel & Places", subcategory: "transport-air", keywords: ["rocket", "space", "launch", "ship", "startup"], description: "A rocket ship." },
  { emoji: "✈️", name: "Airplane", slug: "airplane", category: "Travel & Places", subcategory: "transport-air", keywords: ["plane", "airplane", "flight", "travel"], description: "An airplane." },
  { emoji: "🏠", name: "House", slug: "house", category: "Travel & Places", subcategory: "place-building", keywords: ["house", "home", "building", "residence"], description: "A house." },
  { emoji: "🏢", name: "Office Building", slug: "office-building", category: "Travel & Places", subcategory: "place-building", keywords: ["office", "building", "work", "business"], description: "An office building." },
  { emoji: "🏖️", name: "Beach with Umbrella", slug: "beach-umbrella", category: "Travel & Places", subcategory: "place-geographic", keywords: ["beach", "vacation", "umbrella", "sand", "summer"], description: "A beach with umbrella." },
  { emoji: "🌍", name: "Globe Showing Europe-Africa", slug: "globe-europe-africa", category: "Travel & Places", subcategory: "place-map", keywords: ["earth", "world", "globe", "planet", "international"], description: "Globe showing Europe and Africa." },
  { emoji: "🗽", name: "Statue of Liberty", slug: "statue-of-liberty", category: "Travel & Places", subcategory: "place-building", keywords: ["liberty", "new york", "america", "statue", "freedom"], description: "The Statue of Liberty." },

  // Weather & Sky
  { emoji: "☀️", name: "Sun", slug: "sun", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["sun", "sunny", "hot", "warm", "bright"], description: "A bright sun." },
  { emoji: "🌙", name: "Crescent Moon", slug: "crescent-moon", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["moon", "night", "crescent", "sleep"], description: "A crescent moon." },
  { emoji: "⭐", name: "Star", slug: "star", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["star", "favorite", "night", "shine"], description: "A yellow star." },
  { emoji: "🌟", name: "Glowing Star", slug: "glowing-star", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["star", "glow", "sparkle", "shine"], description: "A glowing star." },
  { emoji: "✨", name: "Sparkles", slug: "sparkles", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["sparkle", "shine", "magic", "clean", "new"], description: "Sparkles." },
  { emoji: "🌈", name: "Rainbow", slug: "rainbow", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["rainbow", "colors", "pride", "weather"], description: "A rainbow." },
  { emoji: "🔥", name: "Fire", slug: "fire", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["fire", "hot", "flame", "lit", "trending"], description: "A flame of fire." },
  { emoji: "💧", name: "Droplet", slug: "droplet", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["water", "rain", "drop", "sweat"], description: "A water droplet." },
  { emoji: "❄️", name: "Snowflake", slug: "snowflake", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["snow", "cold", "winter", "ice", "frozen"], description: "A snowflake." },
  { emoji: "⚡", name: "High Voltage", slug: "high-voltage", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["lightning", "electric", "power", "thunder", "zap"], description: "A lightning bolt." },
  { emoji: "🌊", name: "Water Wave", slug: "water-wave", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["wave", "ocean", "water", "surf", "sea"], description: "An ocean wave." },

  // Objects & Symbols
  { emoji: "💯", name: "Hundred Points", slug: "hundred-points", category: "Objects & Symbols", subcategory: "keycap", keywords: ["100", "perfect", "score", "hundred", "percent"], description: "The number 100 with double underline." },
  { emoji: "💰", name: "Money Bag", slug: "money-bag", category: "Objects & Symbols", subcategory: "money", keywords: ["money", "bag", "dollar", "rich", "cash"], description: "A bag of money." },
  { emoji: "💎", name: "Gem Stone", slug: "gem-stone", category: "Objects & Symbols", subcategory: "money", keywords: ["diamond", "gem", "jewel", "precious", "sparkle"], description: "A sparkling gem stone." },
  { emoji: "🎵", name: "Musical Note", slug: "musical-note", category: "Objects & Symbols", subcategory: "music", keywords: ["music", "note", "song", "melody"], description: "A musical note." },
  { emoji: "🎶", name: "Musical Notes", slug: "musical-notes", category: "Objects & Symbols", subcategory: "music", keywords: ["music", "notes", "song", "melody", "singing"], description: "Musical notes." },
  { emoji: "🔔", name: "Bell", slug: "bell", category: "Objects & Symbols", subcategory: "sound", keywords: ["bell", "notification", "alert", "ring"], description: "A bell." },
  { emoji: "📱", name: "Mobile Phone", slug: "mobile-phone", category: "Objects & Symbols", subcategory: "phone", keywords: ["phone", "mobile", "cell", "smartphone", "iphone"], description: "A mobile phone." },
  { emoji: "💻", name: "Laptop", slug: "laptop", category: "Objects & Symbols", subcategory: "computer", keywords: ["laptop", "computer", "work", "tech", "code"], description: "A laptop computer." },
  { emoji: "📷", name: "Camera", slug: "camera", category: "Objects & Symbols", subcategory: "light-video", keywords: ["camera", "photo", "picture", "photography"], description: "A camera." },
  { emoji: "🎁", name: "Wrapped Gift", slug: "wrapped-gift", category: "Objects & Symbols", subcategory: "event", keywords: ["gift", "present", "birthday", "christmas", "surprise"], description: "A wrapped gift box." },
  { emoji: "🎀", name: "Ribbon", slug: "ribbon", category: "Objects & Symbols", subcategory: "event", keywords: ["ribbon", "bow", "gift", "decoration"], description: "A pink ribbon bow." },
  { emoji: "🎉", name: "Party Popper", slug: "party-popper", category: "Objects & Symbols", subcategory: "event", keywords: ["party", "celebrate", "confetti", "tada", "congratulations"], description: "A party popper with confetti." },
  { emoji: "🎊", name: "Confetti Ball", slug: "confetti-ball", category: "Objects & Symbols", subcategory: "event", keywords: ["confetti", "celebration", "party"], description: "A confetti ball." },
  { emoji: "🎈", name: "Balloon", slug: "balloon", category: "Objects & Symbols", subcategory: "event", keywords: ["balloon", "party", "birthday", "celebration"], description: "A red balloon." },
  { emoji: "🎃", name: "Jack-O-Lantern", slug: "jack-o-lantern", category: "Objects & Symbols", subcategory: "event", keywords: ["halloween", "pumpkin", "jack-o-lantern", "spooky", "october"], description: "A carved pumpkin." },
  { emoji: "🎄", name: "Christmas Tree", slug: "christmas-tree", category: "Objects & Symbols", subcategory: "event", keywords: ["christmas", "tree", "holiday", "xmas", "december"], description: "A decorated Christmas tree." },
  { emoji: "🎅", name: "Santa Claus", slug: "santa-claus", category: "Objects & Symbols", subcategory: "event", keywords: ["santa", "christmas", "holiday", "xmas", "father christmas"], description: "Santa Claus." },
  { emoji: "📝", name: "Memo", slug: "memo", category: "Objects & Symbols", subcategory: "writing", keywords: ["memo", "note", "write", "document", "pencil"], description: "A memo or notepad." },
  { emoji: "📌", name: "Pushpin", slug: "pushpin", category: "Objects & Symbols", subcategory: "office", keywords: ["pin", "pushpin", "location", "mark"], description: "A pushpin." },
  { emoji: "🔑", name: "Key", slug: "key", category: "Objects & Symbols", subcategory: "lock", keywords: ["key", "lock", "password", "security"], description: "A key." },
  { emoji: "🔒", name: "Locked", slug: "locked", category: "Objects & Symbols", subcategory: "lock", keywords: ["lock", "secure", "closed", "private"], description: "A closed padlock." },

  // Flags & Misc
  { emoji: "🏁", name: "Chequered Flag", slug: "chequered-flag", category: "Flags & Symbols", subcategory: "flag", keywords: ["flag", "race", "finish", "checkered"], description: "A checkered flag." },
  { emoji: "🚩", name: "Triangular Flag", slug: "triangular-flag", category: "Flags & Symbols", subcategory: "flag", keywords: ["flag", "red flag", "warning"], description: "A triangular red flag." },
  { emoji: "🏳️‍🌈", name: "Rainbow Flag", slug: "rainbow-flag", category: "Flags & Symbols", subcategory: "flag", keywords: ["pride", "rainbow", "lgbtq", "flag", "gay"], description: "The rainbow pride flag." },
  { emoji: "✅", name: "Check Mark Button", slug: "check-mark-button", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["check", "done", "complete", "yes", "correct"], description: "A green check mark button." },
  { emoji: "❌", name: "Cross Mark", slug: "cross-mark", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["no", "wrong", "delete", "cross", "x"], description: "A red cross mark." },
  { emoji: "❓", name: "Question Mark", slug: "question-mark", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["question", "what", "help", "confused"], description: "A red question mark." },
  { emoji: "❗", name: "Exclamation Mark", slug: "exclamation-mark", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["exclamation", "important", "warning", "alert"], description: "A red exclamation mark." },
  { emoji: "💤", name: "Zzz", slug: "zzz", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["sleep", "zzz", "tired", "snore", "rest"], description: "ZZZ indicating sleep." },
  { emoji: "♻️", name: "Recycling Symbol", slug: "recycling-symbol", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["recycle", "green", "environment", "eco"], description: "The recycling symbol." },
  { emoji: "⚠️", name: "Warning", slug: "warning", category: "Flags & Symbols", subcategory: "other-symbol", keywords: ["warning", "caution", "danger", "alert"], description: "A warning sign." },
  { emoji: "🔴", name: "Red Circle", slug: "red-circle", category: "Flags & Symbols", subcategory: "geometric", keywords: ["red", "circle", "dot"], description: "A red circle." },
  { emoji: "🔵", name: "Blue Circle", slug: "blue-circle", category: "Flags & Symbols", subcategory: "geometric", keywords: ["blue", "circle", "dot"], description: "A blue circle." },
  { emoji: "⬛", name: "Black Large Square", slug: "black-square", category: "Flags & Symbols", subcategory: "geometric", keywords: ["black", "square", "shape"], description: "A black square." },
  { emoji: "⬜", name: "White Large Square", slug: "white-square", category: "Flags & Symbols", subcategory: "geometric", keywords: ["white", "square", "shape"], description: "A white square." },

  // Additional popular emojis
  { emoji: "🥺", name: "Pleading Face", slug: "pleading-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["please", "puppy eyes", "sad", "begging"], description: "A face with big puppy eyes." },
  { emoji: "🫠", name: "Melting Face", slug: "melting-face", category: "Smileys & Emotion", subcategory: "face-smiling", keywords: ["melting", "hot", "disappearing", "embarrassed"], description: "A face melting." },
  { emoji: "🫡", name: "Saluting Face", slug: "saluting-face", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["salute", "respect", "yes sir"], description: "A face doing a salute." },
  { emoji: "🫶", name: "Heart Hands", slug: "heart-hands", category: "Hand Gestures", subcategory: "hands", keywords: ["heart", "love", "hands", "care"], description: "Two hands forming a heart." },
  { emoji: "🥹", name: "Face Holding Back Tears", slug: "face-holding-back-tears", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["emotional", "touched", "grateful", "tears"], description: "A face holding back tears of joy." },
  { emoji: "😮‍💨", name: "Face Exhaling", slug: "face-exhaling", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["sigh", "relief", "exhale", "tired"], description: "A face exhaling." },
  { emoji: "🫣", name: "Face with Peeking Eye", slug: "face-peeking-eye", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["peek", "scared", "curious", "shy"], description: "A face peeking through fingers." },
  { emoji: "🫢", name: "Face with Open Eyes and Hand Over Mouth", slug: "face-open-eyes-hand-mouth", category: "Smileys & Emotion", subcategory: "face-hand", keywords: ["shocked", "surprise", "oops", "gasp"], description: "A shocked face with hand over mouth." },
  { emoji: "🤓", name: "Nerd Face", slug: "nerd-face", category: "Smileys & Emotion", subcategory: "face-glasses", keywords: ["nerd", "geek", "smart", "glasses"], description: "A face with glasses, a nerd." },
  { emoji: "😎", name: "Smiling Face with Sunglasses", slug: "smiling-face-sunglasses", category: "Smileys & Emotion", subcategory: "face-glasses", keywords: ["cool", "sunglasses", "confident", "awesome"], description: "A cool face with sunglasses." },
  { emoji: "🥸", name: "Disguised Face", slug: "disguised-face", category: "Smileys & Emotion", subcategory: "face-glasses", keywords: ["disguise", "groucho", "glasses", "nose", "mustache"], description: "A face in disguise." },
  { emoji: "😮", name: "Face with Open Mouth", slug: "face-open-mouth", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["surprised", "wow", "open mouth", "shocked"], description: "A face with an open mouth." },
  { emoji: "😯", name: "Hushed Face", slug: "hushed-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["hushed", "surprised", "speechless"], description: "A hushed, surprised face." },
  { emoji: "😲", name: "Astonished Face", slug: "astonished-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["astonished", "shocked", "amazed"], description: "An astonished face." },
  { emoji: "🥱", name: "Yawning Face", slug: "yawning-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["yawn", "tired", "bored", "sleepy"], description: "A yawning face." },
  { emoji: "😳", name: "Flushed Face", slug: "flushed-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["flushed", "embarrassed", "blushing", "surprised"], description: "A flushed, embarrassed face." },
  { emoji: "🥲", name: "Smiling Face with Tear", slug: "smiling-face-with-tear", category: "Smileys & Emotion", subcategory: "face-affection", keywords: ["happy", "sad", "grateful", "tear", "bittersweet"], description: "A smiling face with a single tear." },
  { emoji: "😥", name: "Sad but Relieved Face", slug: "sad-but-relieved-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["sad", "relieved", "disappointed"], description: "A sad but relieved face." },
  { emoji: "🫥", name: "Dotted Line Face", slug: "dotted-line-face", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["invisible", "hidden", "disappear"], description: "A face with a dotted outline." },
  { emoji: "😶‍🌫️", name: "Face in Clouds", slug: "face-in-clouds", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["foggy", "confused", "spaced out"], description: "A face hidden in clouds." },

  // More popular emojis for coverage
  { emoji: "🫰", name: "Hand with Index Finger and Thumb Crossed", slug: "finger-thumb-crossed", category: "Hand Gestures", subcategory: "hand-fingers-partial", keywords: ["money", "snap", "heart", "love"], description: "A hand with crossed finger and thumb." },
  { emoji: "🫵", name: "Index Pointing at the Viewer", slug: "index-pointing-viewer", category: "Hand Gestures", subcategory: "hand-single-finger", keywords: ["you", "point", "uncle sam"], description: "A finger pointing at you." },
  { emoji: "🫱", name: "Rightwards Hand", slug: "rightwards-hand", category: "Hand Gestures", subcategory: "hand-fingers-open", keywords: ["hand", "right", "offer"], description: "A hand facing right." },
  { emoji: "🫲", name: "Leftwards Hand", slug: "leftwards-hand", category: "Hand Gestures", subcategory: "hand-fingers-open", keywords: ["hand", "left", "offer"], description: "A hand facing left." },
  { emoji: "✍️", name: "Writing Hand", slug: "writing-hand", category: "Hand Gestures", subcategory: "hand-prop", keywords: ["write", "hand", "pen", "compose"], description: "A hand writing with a pen." },
  { emoji: "🤳", name: "Selfie", slug: "selfie", category: "Hand Gestures", subcategory: "hand-prop", keywords: ["selfie", "phone", "camera", "photo"], description: "A hand taking a selfie." },
  { emoji: "💅", name: "Nail Polish", slug: "nail-polish", category: "Hand Gestures", subcategory: "hand-prop", keywords: ["nails", "beauty", "manicure", "fabulous", "slay"], description: "Painting nails with polish." },

  // Time/Clock
  { emoji: "⏰", name: "Alarm Clock", slug: "alarm-clock", category: "Objects & Symbols", subcategory: "time", keywords: ["alarm", "clock", "time", "wake up", "morning"], description: "An alarm clock." },
  { emoji: "⌛", name: "Hourglass Done", slug: "hourglass-done", category: "Objects & Symbols", subcategory: "time", keywords: ["hourglass", "time", "timer", "sand"], description: "An hourglass with sand at the bottom." },
  { emoji: "⏳", name: "Hourglass Not Done", slug: "hourglass-not-done", category: "Objects & Symbols", subcategory: "time", keywords: ["hourglass", "time", "timer", "waiting"], description: "An hourglass with flowing sand." },

  // More misc
  { emoji: "🧠", name: "Brain", slug: "brain", category: "People & Body", subcategory: "body-parts", keywords: ["brain", "smart", "think", "intelligent", "mind"], description: "A human brain." },
  { emoji: "👀", name: "Eyes", slug: "eyes", category: "People & Body", subcategory: "body-parts", keywords: ["eyes", "look", "see", "watch", "stare"], description: "A pair of eyes looking." },
  { emoji: "👁️", name: "Eye", slug: "eye", category: "People & Body", subcategory: "body-parts", keywords: ["eye", "look", "see", "watch"], description: "A single eye." },
  { emoji: "👅", name: "Tongue", slug: "tongue", category: "People & Body", subcategory: "body-parts", keywords: ["tongue", "taste", "lick"], description: "A tongue sticking out." },
  { emoji: "👄", name: "Mouth", slug: "mouth", category: "People & Body", subcategory: "body-parts", keywords: ["mouth", "lips", "kiss"], description: "A pair of lips." },
  { emoji: "🦷", name: "Tooth", slug: "tooth", category: "People & Body", subcategory: "body-parts", keywords: ["tooth", "dentist", "teeth"], description: "A tooth." },
  { emoji: "🦴", name: "Bone", slug: "bone", category: "People & Body", subcategory: "body-parts", keywords: ["bone", "skeleton", "dog"], description: "A bone." },
  { emoji: "🦶", name: "Foot", slug: "foot", category: "People & Body", subcategory: "body-parts", keywords: ["foot", "kick", "stomp"], description: "A foot." },
  { emoji: "🦵", name: "Leg", slug: "leg", category: "People & Body", subcategory: "body-parts", keywords: ["leg", "kick", "limb"], description: "A leg." },
  { emoji: "👂", name: "Ear", slug: "ear", category: "People & Body", subcategory: "body-parts", keywords: ["ear", "hear", "listen", "sound"], description: "A human ear." },
  { emoji: "👃", name: "Nose", slug: "nose", category: "People & Body", subcategory: "body-parts", keywords: ["nose", "smell", "sniff"], description: "A nose." },

  // Additional popular ones
  { emoji: "🌶️", name: "Hot Pepper", slug: "hot-pepper", category: "Food & Drink", subcategory: "food-vegetable", keywords: ["pepper", "hot", "spicy", "chili"], description: "A hot chili pepper." },
  { emoji: "🍿", name: "Popcorn", slug: "popcorn", category: "Food & Drink", subcategory: "food-prepared", keywords: ["popcorn", "movie", "snack", "cinema"], description: "A box of popcorn." },
  { emoji: "🧁", name: "Cupcake", slug: "cupcake", category: "Food & Drink", subcategory: "food-sweet", keywords: ["cupcake", "sweet", "dessert", "cake"], description: "A cupcake with frosting." },
  { emoji: "🍭", name: "Lollipop", slug: "lollipop", category: "Food & Drink", subcategory: "food-sweet", keywords: ["lollipop", "candy", "sweet", "sugar"], description: "A swirly lollipop." },
  { emoji: "🍬", name: "Candy", slug: "candy", category: "Food & Drink", subcategory: "food-sweet", keywords: ["candy", "sweet", "sugar", "treat"], description: "A wrapped candy." },
  { emoji: "🧊", name: "Ice", slug: "ice", category: "Food & Drink", subcategory: "drink", keywords: ["ice", "cold", "frozen", "cube"], description: "An ice cube." },
  { emoji: "🫧", name: "Bubbles", slug: "bubbles", category: "Objects & Symbols", subcategory: "other-object", keywords: ["bubbles", "soap", "clean", "fun"], description: "Colorful bubbles." },
  { emoji: "🪄", name: "Magic Wand", slug: "magic-wand", category: "Objects & Symbols", subcategory: "other-object", keywords: ["magic", "wand", "sparkle", "wizard"], description: "A magic wand." },
  { emoji: "🔮", name: "Crystal Ball", slug: "crystal-ball", category: "Objects & Symbols", subcategory: "other-object", keywords: ["crystal ball", "fortune", "magic", "predict"], description: "A crystal ball." },
  { emoji: "🧿", name: "Nazar Amulet", slug: "nazar-amulet", category: "Objects & Symbols", subcategory: "other-object", keywords: ["nazar", "evil eye", "protection", "amulet"], description: "A nazar amulet." },
  { emoji: "🪬", name: "Hamsa", slug: "hamsa", category: "Objects & Symbols", subcategory: "other-object", keywords: ["hamsa", "hand", "protection", "luck"], description: "A hamsa hand." },
  { emoji: "💡", name: "Light Bulb", slug: "light-bulb", category: "Objects & Symbols", subcategory: "light-video", keywords: ["idea", "light", "bulb", "think", "bright"], description: "A glowing light bulb." },
  { emoji: "📚", name: "Books", slug: "books", category: "Objects & Symbols", subcategory: "book-paper", keywords: ["books", "reading", "library", "study", "education"], description: "A stack of books." },
  { emoji: "✏️", name: "Pencil", slug: "pencil", category: "Objects & Symbols", subcategory: "writing", keywords: ["pencil", "write", "edit", "draw"], description: "A pencil." },
  { emoji: "🖊️", name: "Pen", slug: "pen", category: "Objects & Symbols", subcategory: "writing", keywords: ["pen", "write", "ink"], description: "A pen." },
  { emoji: "🎤", name: "Microphone", slug: "microphone", category: "Objects & Symbols", subcategory: "music", keywords: ["microphone", "sing", "karaoke", "music", "voice"], description: "A microphone." },
  { emoji: "🎧", name: "Headphone", slug: "headphone", category: "Objects & Symbols", subcategory: "music", keywords: ["headphones", "music", "listen", "audio"], description: "A pair of headphones." },
  { emoji: "🎬", name: "Clapper Board", slug: "clapper-board", category: "Objects & Symbols", subcategory: "light-video", keywords: ["movie", "film", "cinema", "action", "clapper"], description: "A movie clapper board." },
  { emoji: "📺", name: "Television", slug: "television", category: "Objects & Symbols", subcategory: "computer", keywords: ["tv", "television", "watch", "screen"], description: "A television." },
  { emoji: "🔗", name: "Link", slug: "link", category: "Objects & Symbols", subcategory: "tool", keywords: ["link", "chain", "url", "connect"], description: "A chain link." },
  { emoji: "🔧", name: "Wrench", slug: "wrench", category: "Objects & Symbols", subcategory: "tool", keywords: ["wrench", "tool", "fix", "repair"], description: "A wrench." },
  { emoji: "⚙️", name: "Gear", slug: "gear", category: "Objects & Symbols", subcategory: "tool", keywords: ["gear", "settings", "cog", "configure"], description: "A gear cog." },

  // Zodiac & additional symbols
  { emoji: "♈", name: "Aries", slug: "aries", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["aries", "zodiac", "horoscope", "astrology"], description: "The Aries zodiac sign." },
  { emoji: "♉", name: "Taurus", slug: "taurus", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["taurus", "zodiac", "horoscope", "astrology"], description: "The Taurus zodiac sign." },
  { emoji: "♊", name: "Gemini", slug: "gemini", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["gemini", "zodiac", "horoscope", "astrology"], description: "The Gemini zodiac sign." },
  { emoji: "♋", name: "Cancer", slug: "cancer-zodiac", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["cancer", "zodiac", "horoscope", "astrology"], description: "The Cancer zodiac sign." },
  { emoji: "♌", name: "Leo", slug: "leo", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["leo", "zodiac", "horoscope", "astrology"], description: "The Leo zodiac sign." },
  { emoji: "♍", name: "Virgo", slug: "virgo", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["virgo", "zodiac", "horoscope", "astrology"], description: "The Virgo zodiac sign." },
  { emoji: "♎", name: "Libra", slug: "libra", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["libra", "zodiac", "horoscope", "astrology"], description: "The Libra zodiac sign." },
  { emoji: "♏", name: "Scorpio", slug: "scorpio", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["scorpio", "zodiac", "horoscope", "astrology"], description: "The Scorpio zodiac sign." },
  { emoji: "♐", name: "Sagittarius", slug: "sagittarius", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["sagittarius", "zodiac", "horoscope", "astrology"], description: "The Sagittarius zodiac sign." },
  { emoji: "♑", name: "Capricorn", slug: "capricorn", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["capricorn", "zodiac", "horoscope", "astrology"], description: "The Capricorn zodiac sign." },
  { emoji: "♒", name: "Aquarius", slug: "aquarius", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["aquarius", "zodiac", "horoscope", "astrology"], description: "The Aquarius zodiac sign." },
  { emoji: "♓", name: "Pisces", slug: "pisces", category: "Flags & Symbols", subcategory: "zodiac", keywords: ["pisces", "zodiac", "horoscope", "astrology"], description: "The Pisces zodiac sign." },

  // More daily-use emojis
  { emoji: "🛒", name: "Shopping Cart", slug: "shopping-cart", category: "Objects & Symbols", subcategory: "other-object", keywords: ["shopping", "cart", "buy", "store"], description: "A shopping cart." },
  { emoji: "💊", name: "Pill", slug: "pill", category: "Objects & Symbols", subcategory: "medical", keywords: ["pill", "medicine", "drug", "health"], description: "A medicine pill." },
  { emoji: "🩹", name: "Adhesive Bandage", slug: "adhesive-bandage", category: "Objects & Symbols", subcategory: "medical", keywords: ["bandage", "band-aid", "healing", "hurt"], description: "An adhesive bandage." },
  { emoji: "🪞", name: "Mirror", slug: "mirror", category: "Objects & Symbols", subcategory: "other-object", keywords: ["mirror", "reflection", "beauty"], description: "A mirror." },
  { emoji: "🧸", name: "Teddy Bear", slug: "teddy-bear", category: "Objects & Symbols", subcategory: "other-object", keywords: ["teddy bear", "toy", "cute", "stuffed animal"], description: "A teddy bear." },
  { emoji: "🪴", name: "Potted Plant", slug: "potted-plant", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["plant", "pot", "houseplant", "green"], description: "A potted plant." },
  { emoji: "🍄", name: "Mushroom", slug: "mushroom", category: "Plants & Flowers", subcategory: "plant-other", keywords: ["mushroom", "fungus", "toadstool"], description: "A red and white mushroom." },
  { emoji: "🐾", name: "Paw Prints", slug: "paw-prints", category: "Animals & Nature", subcategory: "animal-mammal", keywords: ["paw", "prints", "animal", "pet", "dog", "cat"], description: "Animal paw prints." },
  { emoji: "🕊️", name: "Dove", slug: "dove", category: "Animals & Nature", subcategory: "animal-bird", keywords: ["dove", "peace", "bird", "white"], description: "A white dove of peace." },
  { emoji: "🦋", name: "Butterfly Duplicate Removed", slug: "butterfly-2", category: "Animals & Nature", subcategory: "animal-bug", keywords: ["butterfly", "insect", "wings"], description: "A colorful butterfly." },

  // Expressions additions
  { emoji: "🫤", name: "Face with Diagonal Mouth", slug: "face-diagonal-mouth", category: "Smileys & Emotion", subcategory: "face-neutral", keywords: ["skeptical", "unsure", "meh", "disappointed"], description: "A face with a skewed mouth." },
  { emoji: "😞", name: "Disappointed Face", slug: "disappointed-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["sad", "disappointed", "upset", "down"], description: "A disappointed, frowning face." },
  { emoji: "😓", name: "Downcast Face with Sweat", slug: "downcast-face-sweat", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["sad", "sweat", "hard work", "stressed"], description: "A sad face with a bead of sweat." },
  { emoji: "😩", name: "Weary Face", slug: "weary-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["weary", "tired", "frustrated", "exhausted"], description: "A weary, exhausted face." },
  { emoji: "😫", name: "Tired Face", slug: "tired-face", category: "Smileys & Emotion", subcategory: "face-concerned", keywords: ["tired", "exhausted", "fed up"], description: "An extremely tired face." },
  { emoji: "🤯", name: "Exploding Head", slug: "exploding-head", category: "Smileys & Emotion", subcategory: "face-unwell", keywords: ["mind blown", "shocked", "amazed", "exploding"], description: "A head exploding in shock." },
  { emoji: "😤", name: "Huffing Face", slug: "huffing-face", category: "Smileys & Emotion", subcategory: "face-negative", keywords: ["triumph", "frustrated", "steam", "angry"], description: "A face huffing with triumph." },

  // Occupation/Activity people
  { emoji: "💃", name: "Woman Dancing", slug: "woman-dancing", category: "People & Body", subcategory: "person-activity", keywords: ["dance", "woman", "salsa", "party"], description: "A woman dancing." },
  { emoji: "🕺", name: "Man Dancing", slug: "man-dancing", category: "People & Body", subcategory: "person-activity", keywords: ["dance", "man", "disco", "party"], description: "A man dancing." },
  { emoji: "🧘", name: "Person in Lotus Position", slug: "person-lotus-position", category: "People & Body", subcategory: "person-activity", keywords: ["yoga", "meditate", "zen", "calm"], description: "A person meditating in lotus position." },
  { emoji: "🏃", name: "Person Running", slug: "person-running", category: "People & Body", subcategory: "person-activity", keywords: ["run", "jog", "exercise", "sprint"], description: "A person running." },
  { emoji: "🚶", name: "Person Walking", slug: "person-walking", category: "People & Body", subcategory: "person-activity", keywords: ["walk", "stroll", "pedestrian"], description: "A person walking." },

  // Tech emojis
  { emoji: "🖥️", name: "Desktop Computer", slug: "desktop-computer", category: "Objects & Symbols", subcategory: "computer", keywords: ["computer", "desktop", "monitor", "screen"], description: "A desktop computer." },
  { emoji: "⌨️", name: "Keyboard", slug: "keyboard", category: "Objects & Symbols", subcategory: "computer", keywords: ["keyboard", "type", "computer", "coding"], description: "A keyboard." },
  { emoji: "🖱️", name: "Computer Mouse", slug: "computer-mouse", category: "Objects & Symbols", subcategory: "computer", keywords: ["mouse", "computer", "click", "cursor"], description: "A computer mouse." },
  { emoji: "💾", name: "Floppy Disk", slug: "floppy-disk", category: "Objects & Symbols", subcategory: "computer", keywords: ["floppy", "save", "disk", "retro"], description: "A floppy disk." },
  { emoji: "📡", name: "Satellite Antenna", slug: "satellite-antenna", category: "Objects & Symbols", subcategory: "computer", keywords: ["satellite", "signal", "broadcast", "antenna"], description: "A satellite antenna." },

  // More nature/weather
  { emoji: "🌤️", name: "Sun Behind Small Cloud", slug: "sun-behind-small-cloud", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["sunny", "cloud", "weather", "partly cloudy"], description: "Sun behind a small cloud." },
  { emoji: "⛈️", name: "Cloud with Lightning and Rain", slug: "cloud-lightning-rain", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["storm", "thunder", "rain", "lightning"], description: "A storm cloud with lightning and rain." },
  { emoji: "🌪️", name: "Tornado", slug: "tornado", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["tornado", "twister", "wind", "storm"], description: "A tornado." },
  { emoji: "🌫️", name: "Fog", slug: "fog", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["fog", "mist", "hazy", "cloudy"], description: "Fog." },
  { emoji: "☁️", name: "Cloud", slug: "cloud", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["cloud", "weather", "sky", "overcast"], description: "A white cloud." },
  { emoji: "🌕", name: "Full Moon", slug: "full-moon", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["moon", "full", "night", "bright"], description: "A full moon." },
  { emoji: "🌑", name: "New Moon", slug: "new-moon", category: "Weather & Sky", subcategory: "sky-weather", keywords: ["moon", "new", "dark", "night"], description: "A new moon." },

  // Additional symbols / arrows
  { emoji: "➡️", name: "Right Arrow", slug: "right-arrow", category: "Flags & Symbols", subcategory: "arrow", keywords: ["right", "arrow", "direction", "next"], description: "A right-pointing arrow." },
  { emoji: "⬅️", name: "Left Arrow", slug: "left-arrow", category: "Flags & Symbols", subcategory: "arrow", keywords: ["left", "arrow", "direction", "back"], description: "A left-pointing arrow." },
  { emoji: "⬆️", name: "Up Arrow", slug: "up-arrow", category: "Flags & Symbols", subcategory: "arrow", keywords: ["up", "arrow", "direction"], description: "An up-pointing arrow." },
  { emoji: "⬇️", name: "Down Arrow", slug: "down-arrow", category: "Flags & Symbols", subcategory: "arrow", keywords: ["down", "arrow", "direction"], description: "A down-pointing arrow." },
  { emoji: "↩️", name: "Right Arrow Curving Left", slug: "right-arrow-curving-left", category: "Flags & Symbols", subcategory: "arrow", keywords: ["return", "back", "arrow", "reply"], description: "A right arrow curving left." },
  { emoji: "🔄", name: "Counterclockwise Arrows Button", slug: "counterclockwise-arrows", category: "Flags & Symbols", subcategory: "arrow", keywords: ["refresh", "reload", "sync", "repeat"], description: "Two counterclockwise arrows." },
  { emoji: "🔃", name: "Clockwise Vertical Arrows", slug: "clockwise-vertical-arrows", category: "Flags & Symbols", subcategory: "arrow", keywords: ["rotate", "refresh", "cycle"], description: "Two clockwise vertical arrows." },

  // Math/number
  { emoji: "➕", name: "Plus", slug: "plus", category: "Flags & Symbols", subcategory: "math", keywords: ["plus", "add", "math", "positive"], description: "A plus sign." },
  { emoji: "➖", name: "Minus", slug: "minus", category: "Flags & Symbols", subcategory: "math", keywords: ["minus", "subtract", "math", "negative"], description: "A minus sign." },
  { emoji: "✖️", name: "Multiply", slug: "multiply", category: "Flags & Symbols", subcategory: "math", keywords: ["multiply", "times", "math", "x"], description: "A multiplication sign." },
  { emoji: "➗", name: "Divide", slug: "divide", category: "Flags & Symbols", subcategory: "math", keywords: ["divide", "math", "division"], description: "A division sign." },
  { emoji: "♾️", name: "Infinity", slug: "infinity", category: "Flags & Symbols", subcategory: "math", keywords: ["infinity", "forever", "endless", "unlimited"], description: "The infinity symbol." },

  // More activities
  { emoji: "🎨", name: "Artist Palette", slug: "artist-palette", category: "Activities & Sports", subcategory: "arts-crafts", keywords: ["art", "paint", "palette", "creative", "draw"], description: "An artist's palette with paint." },
  { emoji: "🎭", name: "Performing Arts", slug: "performing-arts", category: "Activities & Sports", subcategory: "arts-crafts", keywords: ["theater", "drama", "acting", "masks", "comedy", "tragedy"], description: "Theater masks." },
  { emoji: "🎸", name: "Guitar", slug: "guitar", category: "Activities & Sports", subcategory: "musical-instrument", keywords: ["guitar", "music", "rock", "instrument"], description: "An electric guitar." },
  { emoji: "🎹", name: "Musical Keyboard", slug: "musical-keyboard", category: "Activities & Sports", subcategory: "musical-instrument", keywords: ["piano", "keyboard", "music", "instrument"], description: "A musical keyboard." },
  { emoji: "🎺", name: "Trumpet", slug: "trumpet", category: "Activities & Sports", subcategory: "musical-instrument", keywords: ["trumpet", "music", "jazz", "instrument"], description: "A trumpet." },
  { emoji: "🥁", name: "Drum", slug: "drum", category: "Activities & Sports", subcategory: "musical-instrument", keywords: ["drum", "music", "beat", "percussion"], description: "A snare drum." },
  { emoji: "🏋️", name: "Person Lifting Weights", slug: "person-lifting-weights", category: "Activities & Sports", subcategory: "sport", keywords: ["gym", "weights", "exercise", "strong", "fitness"], description: "A person lifting weights." },
  { emoji: "🤸", name: "Person Cartwheeling", slug: "person-cartwheeling", category: "Activities & Sports", subcategory: "sport", keywords: ["cartwheel", "gymnastics", "flexible"], description: "A person cartwheeling." },
  { emoji: "🏊", name: "Person Swimming", slug: "person-swimming", category: "Activities & Sports", subcategory: "sport", keywords: ["swim", "pool", "water", "exercise"], description: "A person swimming." },
  { emoji: "🚴", name: "Person Biking", slug: "person-biking", category: "Activities & Sports", subcategory: "sport", keywords: ["bike", "cycling", "bicycle", "exercise"], description: "A person riding a bicycle." },

  // Additional popular
  { emoji: "🩷", name: "Pink Heart", slug: "pink-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "pink", "heart", "cute"], description: "A pink heart." },
  { emoji: "🩵", name: "Light Blue Heart", slug: "light-blue-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "light blue", "heart", "calm"], description: "A light blue heart." },
  { emoji: "🩶", name: "Grey Heart", slug: "grey-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "grey", "heart", "neutral"], description: "A grey heart." },
  { emoji: "❤️‍🔥", name: "Heart on Fire", slug: "heart-on-fire", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "fire", "passion", "burning", "desire"], description: "A heart engulfed in flames." },
  { emoji: "❤️‍🩹", name: "Mending Heart", slug: "mending-heart", category: "Hearts & Love", subcategory: "heart", keywords: ["love", "healing", "recover", "bandage"], description: "A heart with a bandage, mending." },
];

export const TOP_KEYWORDS: string[] = [
  "happy emoji", "sad emoji", "love emoji", "heart emoji", "laugh emoji",
  "cry emoji", "angry emoji", "fire emoji", "thumbs up emoji", "party emoji",
  "kiss emoji", "cool emoji", "thinking emoji", "prayer emoji", "clap emoji",
  "star emoji", "sun emoji", "moon emoji", "rainbow emoji", "sparkle emoji",
  "muscle emoji", "peace emoji", "wave emoji", "point emoji", "ok emoji",
  "skull emoji", "ghost emoji", "alien emoji", "robot emoji", "poop emoji",
  "dog emoji", "cat emoji", "unicorn emoji", "butterfly emoji", "flower emoji",
  "rose emoji", "christmas emoji", "halloween emoji", "birthday emoji", "gift emoji",
  "pizza emoji", "coffee emoji", "beer emoji", "ice cream emoji", "cake emoji",
  "basketball emoji", "soccer emoji", "trophy emoji", "video game emoji", "music emoji",
  "rocket emoji", "car emoji", "airplane emoji", "house emoji", "money emoji",
  "diamond emoji", "crown emoji", "phone emoji", "laptop emoji", "camera emoji",
  "book emoji", "pen emoji", "bulb emoji", "key emoji", "link emoji",
  "check emoji", "cross emoji", "warning emoji", "question emoji", "exclamation emoji",
  "100 emoji", "infinity emoji", "recycle emoji", "zzz emoji", "red circle emoji",
  "broken heart emoji", "two hearts emoji", "sparkling heart emoji", "heart eyes emoji", "blowing kiss emoji",
  "smiling face emoji", "winking face emoji", "sunglasses emoji", "nerd emoji", "clown emoji",
  "monkey emoji", "bear emoji", "panda emoji", "fox emoji", "lion emoji",
  "frog emoji", "snake emoji", "dolphin emoji", "shark emoji", "whale emoji",
  "tree emoji", "cactus emoji", "mushroom emoji", "four leaf clover emoji", "maple leaf emoji",
  "hamburger emoji", "taco emoji", "sushi emoji", "avocado emoji", "strawberry emoji",
  "peach emoji", "watermelon emoji", "banana emoji", "cherry emoji", "grape emoji",
  "brain emoji", "eyes emoji", "tongue emoji", "ear emoji", "nose emoji",
  "baby emoji", "old man emoji", "woman emoji", "man emoji", "dancing emoji",
  "running emoji", "yoga emoji", "selfie emoji", "nail polish emoji", "writing hand emoji",
  "alarm clock emoji", "hourglass emoji", "crystal ball emoji", "magic wand emoji", "teddy bear emoji",
  "american football emoji", "baseball emoji", "tennis emoji", "medal emoji", "art emoji",
  "guitar emoji", "piano emoji", "drum emoji", "microphone emoji", "headphones emoji",
  "tv emoji", "movie emoji", "dice emoji", "bullseye emoji", "flag emoji",
  "confetti emoji", "balloon emoji", "ribbon emoji", "bell emoji", "megaphone emoji",
  "arrow emoji", "plus emoji", "minus emoji", "gear emoji", "wrench emoji",
  "lock emoji", "pin emoji", "memo emoji", "scissors emoji", "calendar emoji",
  "clock emoji", "magnifying glass emoji", "telescope emoji", "microscope emoji", "dna emoji",
  "pill emoji", "bandage emoji", "shopping cart emoji", "credit card emoji", "envelope emoji",
  "zodiac emoji", "aries emoji", "taurus emoji", "gemini emoji", "cancer emoji",
  "leo emoji", "virgo emoji", "libra emoji", "scorpio emoji", "sagittarius emoji",
  "capricorn emoji", "aquarius emoji", "pisces emoji", "pride emoji", "peace sign emoji",
  "rock on emoji", "call me emoji", "pinched fingers emoji", "fist bump emoji", "handshake emoji",
  "exploding head emoji", "melting face emoji", "pleading face emoji", "yawning emoji", "cold face emoji",
  "hot face emoji", "dizzy emoji", "nausea emoji", "sick emoji", "mask emoji",
  "sleeping emoji", "drooling emoji", "shush emoji", "zipper mouth emoji", "smirk emoji",
  "unamused emoji", "eye roll emoji", "grimace emoji", "liar emoji", "devil emoji",
  "angel emoji", "santa emoji", "pumpkin emoji", "christmas tree emoji", "fireworks emoji",
  "snow emoji", "rain emoji", "thunder emoji", "tornado emoji", "fog emoji",
  "sunrise emoji", "sunset emoji", "camping emoji", "tent emoji", "mountain emoji",
  "volcano emoji", "desert emoji", "island emoji", "beach emoji", "wave emoji",
  "surfing emoji", "skiing emoji", "snowboard emoji", "swimming emoji", "biking emoji",
  "horse emoji", "chicken emoji", "pig emoji", "cow emoji", "bee emoji",
  "ladybug emoji", "spider emoji", "ant emoji", "turtle emoji", "octopus emoji",
  "penguin emoji", "eagle emoji", "dove emoji", "flamingo emoji", "parrot emoji",
  "potted plant emoji", "herb emoji", "leaf emoji", "fallen leaf emoji", "blossom emoji",
  "cherry blossom emoji", "sunflower emoji", "tulip emoji", "hibiscus emoji", "bouquet emoji",
  "paw print emoji", "footprint emoji", "bone emoji", "tooth emoji", "leg emoji",
  "cookie emoji", "donut emoji", "candy emoji", "lollipop emoji", "cupcake emoji",
  "popcorn emoji", "hot pepper emoji", "corn emoji", "carrot emoji", "broccoli emoji",
  "wine emoji", "cocktail emoji", "juice emoji", "milk emoji", "tea emoji",
  "bubbles emoji", "mirror emoji", "shopping bag emoji", "handbag emoji", "backpack emoji",
  "crown emoji copy paste", "fire emoji copy paste", "heart emoji copy paste", "star emoji copy paste",
  "skull emoji copy paste", "laugh cry emoji", "side eye emoji", "sobbing emoji", "anxious emoji",
  "weary emoji", "tired emoji", "disappointed emoji", "stressed emoji", "relieved emoji",
  "embarrassed emoji", "flushed emoji", "bittersweet emoji", "salute emoji", "peeking emoji",
  "heart hands emoji", "holding back tears emoji", "exhaling emoji", "dotted face emoji",
  "invisible emoji", "diagonal mouth emoji", "face in clouds emoji",
];

export function generateSeoPages(keywords: string[]): InsertEmojiPage[] {
  return keywords.map(keyword => ({
    slug: slugify(keyword),
    title: `${keyword.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} - Copy & Paste`,
    keyword,
    metaDescription: `Copy and paste ${keyword} instantly! Find the best ${keyword} to use in messages, social media, and more. One click copy.`,
    relatedEmojis: [],
    isGenerated: false,
  }));
}
